Questionfour

In [1]:
#an inverse of a matrix
import numpy as np

In [2]:
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])
print("Original Matrix:")
print(matrix)

Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [3]:
# Compute the inverse (transpose)
inverse_matrix = np.linalg.inv(matrix)
print("\nInverse of the Matrix (Transpose):")
print(inverse_matrix)





Inverse of the Matrix (Transpose):
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [4]:
#determinant of a matrix
determinant = np.linalg.det(matrix)
print("\nDeterminant of the Matrix:")
print(determinant)


Determinant of the Matrix:
0.2299999999999999


In [5]:
#decompose the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("\nEigenvalues:")
print(eigenvalues)


Eigenvalues:
[2.04100779 0.82188052 0.13711169]


In [ ]:
#transform the matrix
print("\nTransformed Matrix:")
print(transformed_matrix)


Question five

In [7]:


import numpy as np

# Coefficients matrix a
a= np.array([[2, 1, -1],[-3, -1, 2],[-2, 1, 2]])

# Constants vector b
b = np.array([8, -11, -3])

# Solve the system of equations
X = np.linalg.solve(a, b)

# Print the solution
print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution:
x = 2.0000000000000004
y = 2.9999999999999996
z = -0.9999999999999994
